import { Snapshot } from '@disco/schema';

/**
 * A HIGHER-FIDELITY "production trace" snapshot — a realistic, anonymized slots/gambling community of
 * the size and shape Disco actually sells (~$30k template territory), not the tiny `makeSampleSnapshot`
 * fixture. Branded for creator "Stakehaus" (violet #6d28d9, link https://whop.com/stakehaus) so tests,
 * demos, and seeders can exercise the full surface area: 6 categories, ~22 channels (system_content +
 * member_chat + a tagged forum + voice), 10 roles incl. a managed bot role, custom emojis & stickers,
 * automod, detected third-party bots with config traces, a 5-card welcome screen, and rich channel
 * content with interactive components. Every cross-reference uses internal localRefs only. (§3)
 */
export function makeProductionTraceSnapshot(): Snapshot {
  return Snapshot.parse({
    capturedAt: '2026-06-22T18:30:00.000Z',
    source: {
      guildId: '982734651029384756',
      name: 'Stakehaus | Slots & Casino',
      ownerNote: 'High-roller slots community. ~14k members, MEE6 leveling + Whop gated VIP + tickets.',
    },
    guild: {
      name: 'Stakehaus | Slots & Casino',
      verificationLevel: 3,
      defaultMessageNotifications: 1,
      explicitContentFilter: 2,
      afkChannelRef: 'chan_afk',
      afkTimeout: 900,
      systemChannelRef: 'chan_welcome',
      systemChannelFlags: 4,
      rulesChannelRef: 'chan_rules',
      publicUpdatesChannelRef: 'chan_announcements',
      preferredLocale: 'en-US',
      premiumTier: 3,
      assets: {
        icon: 'assets/a1b2c3d4e5f60718.png',
        banner: 'assets/0f9e8d7c6b5a4231.png',
        splash: 'assets/112233445566778899aabbccdd.png',
      },
      welcomeScreen: {
        enabled: true,
        description: 'Welcome to Stakehaus — grab your roles and start hunting bonuses.',
        welcomeChannels: [
          { channelRef: 'chan_rules', description: 'Read the rules first', emojiUnicode: '📜' },
          { channelRef: 'chan_role_select', description: 'Pick your roles', emojiUnicode: '🎭' },
          { channelRef: 'chan_announcements', description: 'Drops & giveaways', emojiUnicode: '📣' },
          { channelRef: 'chan_general', description: 'Say hi to the haus', emojiUnicode: '💬' },
          { channelRef: 'chan_big_wins', description: 'Post your big wins', emojiRef: 'emoji_jackpot' },
        ],
      },
    },
    roles: [
      {
        localRef: 'role_everyone',
        sourceId: '982734651029384756',
        name: '@everyone',
        isEveryone: true,
        colors: { primary: 0 },
        position: 0,
        permissions: '104324673',
      },
      {
        localRef: 'role_owner',
        sourceId: '982734700000000001',
        name: 'Owner',
        colors: { primary: 0x6d28d9 },
        hoist: true,
        position: 9,
        permissions: '1099511627775',
        mentionable: false,
      },
      {
        localRef: 'role_admin',
        sourceId: '982734700000000002',
        name: 'Admin',
        colors: { primary: 0xff5a8a },
        hoist: true,
        position: 8,
        permissions: '8',
        mentionable: true,
      },
      {
        localRef: 'role_mod',
        sourceId: '982734700000000003',
        name: 'Moderator',
        colors: { primary: 0x54e0b0 },
        hoist: true,
        position: 7,
        permissions: '1290157103',
        mentionable: true,
      },
      {
        localRef: 'role_whale',
        sourceId: '982734700000000004',
        name: 'Whale 🐋',
        colors: { primary: 0xe8b341, secondary: 0x6d28d9 },
        hoist: true,
        position: 6,
        permissions: '0',
        mentionable: true,
        unicodeEmoji: '🐋',
      },
      {
        localRef: 'role_vip',
        sourceId: '982734700000000005',
        name: 'Stakehaus VIP',
        colors: { primary: 0x6d28d9 },
        hoist: true,
        position: 5,
        permissions: '0',
        mentionable: true,
      },
      {
        localRef: 'role_booster',
        sourceId: '982734700000000006',
        name: 'Server Booster',
        colors: { primary: 0xf47fff },
        hoist: false,
        position: 4,
        permissions: '0',
        mentionable: false,
        tags: { premiumSubscriber: true },
      },
      {
        localRef: 'role_content',
        sourceId: '982734700000000007',
        name: 'Content Creator',
        colors: { primary: 0x7c6cf0 },
        hoist: false,
        position: 3,
        permissions: '0',
        mentionable: true,
      },
      {
        localRef: 'role_member',
        sourceId: '982734700000000008',
        name: 'Member',
        colors: { primary: 0 },
        hoist: false,
        position: 2,
        permissions: '0',
        mentionable: false,
      },
      {
        localRef: 'role_mee6',
        sourceId: '159985870458322944',
        name: 'MEE6',
        colors: { primary: 0x1abc9c },
        hoist: false,
        position: 1,
        permissions: '268823632',
        managed: true,
        tags: { botId: '159985870458322944' },
      },
    ],
    categories: [
      { localRef: 'cat_welcome', name: 'WELCOME', position: 0 },
      { localRef: 'cat_information', name: 'INFORMATION', position: 1 },
      { localRef: 'cat_community', name: 'COMMUNITY', position: 2 },
      { localRef: 'cat_slots', name: 'SLOTS', position: 3 },
      {
        localRef: 'cat_vip',
        name: 'VIP LOUNGE',
        position: 4,
        overwrites: [
          { targetType: 'role', targetRef: 'role_everyone', allow: '0', deny: '1024' },
          { targetType: 'role', targetRef: 'role_vip', allow: '1024', deny: '0' },
          { targetType: 'role', targetRef: 'role_whale', allow: '1024', deny: '0' },
        ],
      },
      { localRef: 'cat_voice', name: 'VOICE', position: 5 },
    ],
    channels: [
      // ── WELCOME ──────────────────────────────────────────────────────────────
      {
        localRef: 'chan_welcome',
        sourceId: '982734800000000001',
        kind: 'text',
        name: 'welcome',
        categoryRef: 'cat_welcome',
        position: 0,
        topic: 'New here? Start in #rules then grab roles. https://whop.com/stakehaus',
        copyPolicy: 'system_content',
        copyContent: true,
        overwrites: [
          { targetType: 'role', targetRef: 'role_everyone', allow: '1024', deny: '2048' },
        ],
      },
      {
        localRef: 'chan_rules',
        sourceId: '982734800000000002',
        kind: 'text',
        name: 'rules',
        categoryRef: 'cat_welcome',
        position: 1,
        topic: 'Stakehaus community rules. 18+ only. Gamble responsibly — https://whop.com/stakehaus',
        copyPolicy: 'system_content',
        copyContent: true,
        overwrites: [
          { targetType: 'role', targetRef: 'role_everyone', allow: '1024', deny: '2048' },
          { targetType: 'role', targetRef: 'role_mod', allow: '2048', deny: '0' },
        ],
      },
      {
        localRef: 'chan_role_select',
        sourceId: '982734800000000003',
        kind: 'text',
        name: 'role-select',
        categoryRef: 'cat_welcome',
        position: 2,
        topic: 'React or click to pick your roles.',
        copyPolicy: 'system_content',
        copyContent: true,
        overwrites: [
          { targetType: 'role', targetRef: 'role_everyone', allow: '1024', deny: '2048' },
        ],
      },
      // ── INFORMATION ──────────────────────────────────────────────────────────
      {
        localRef: 'chan_announcements',
        sourceId: '982734800000000004',
        kind: 'announcement',
        name: 'announcements',
        categoryRef: 'cat_information',
        position: 0,
        topic: 'Official Stakehaus drops, giveaways & schedule.',
        copyPolicy: 'system_content',
        copyContent: true,
        overwrites: [
          { targetType: 'role', targetRef: 'role_everyone', allow: '0', deny: '2048' },
          { targetType: 'role', targetRef: 'role_admin', allow: '2048', deny: '0' },
        ],
      },
      {
        localRef: 'chan_faq',
        sourceId: '982734800000000005',
        kind: 'text',
        name: 'faq',
        categoryRef: 'cat_information',
        position: 1,
        topic: 'Frequently asked questions about Stakehaus, VIP and bonuses.',
        copyPolicy: 'system_content',
        copyContent: true,
      },
      {
        localRef: 'chan_links',
        sourceId: '982734800000000006',
        kind: 'text',
        name: 'links',
        categoryRef: 'cat_information',
        position: 2,
        topic: 'All official Stakehaus links — beware impersonators.',
        copyPolicy: 'system_content',
        copyContent: true,
      },
      {
        localRef: 'chan_mod_log',
        sourceId: '982734800000000007',
        kind: 'text',
        name: 'mod-log',
        categoryRef: 'cat_information',
        position: 3,
        topic: 'AutoMod alerts & moderation log.',
        copyPolicy: 'member_chat',
        overwrites: [
          { targetType: 'role', targetRef: 'role_everyone', allow: '0', deny: '1024' },
          { targetType: 'role', targetRef: 'role_mod', allow: '1024', deny: '0' },
          { targetType: 'member', targetRef: 'member_344556677889900112', allow: '1024', deny: '0' },
        ],
      },
      // ── COMMUNITY ────────────────────────────────────────────────────────────
      {
        localRef: 'chan_general',
        sourceId: '982734800000000008',
        kind: 'text',
        name: 'general',
        categoryRef: 'cat_community',
        position: 0,
        topic: 'General chat. Keep it friendly.',
        rateLimitPerUser: 3,
        copyPolicy: 'member_chat',
      },
      {
        localRef: 'chan_clips',
        sourceId: '982734800000000009',
        kind: 'text',
        name: 'clips',
        categoryRef: 'cat_community',
        position: 1,
        topic: 'Drop your stream clips & highlight reels.',
        copyPolicy: 'member_chat',
      },
      {
        localRef: 'chan_wins',
        sourceId: '982734800000000010',
        kind: 'text',
        name: 'wins',
        categoryRef: 'cat_community',
        position: 2,
        topic: 'Small & medium wins go here. Big wins → #big-wins.',
        copyPolicy: 'member_chat',
      },
      {
        localRef: 'chan_off_topic',
        sourceId: '982734800000000011',
        kind: 'text',
        name: 'off-topic',
        categoryRef: 'cat_community',
        position: 3,
        topic: 'Anything goes (within the rules).',
        copyPolicy: 'member_chat',
      },
      {
        localRef: 'chan_memes',
        sourceId: '982734800000000012',
        kind: 'text',
        name: 'memes',
        categoryRef: 'cat_community',
        position: 4,
        topic: 'Post your dankest slot memes.',
        nsfw: false,
        copyPolicy: 'member_chat',
      },
      // ── SLOTS ────────────────────────────────────────────────────────────────
      {
        localRef: 'chan_strategy',
        sourceId: '982734800000000013',
        kind: 'text',
        name: 'strategy',
        categoryRef: 'cat_slots',
        position: 0,
        topic: 'Bankroll management & bonus-hunting strategy talk.',
        copyPolicy: 'member_chat',
      },
      {
        localRef: 'chan_bonus_codes',
        sourceId: '982734800000000014',
        kind: 'text',
        name: 'bonus-codes',
        categoryRef: 'cat_slots',
        position: 1,
        topic: 'Daily bonus & promo codes. Posted by staff only.',
        copyPolicy: 'system_content',
        copyContent: true,
        overwrites: [
          { targetType: 'role', targetRef: 'role_everyone', allow: '0', deny: '2048' },
          { targetType: 'role', targetRef: 'role_mod', allow: '2048', deny: '0' },
        ],
      },
      {
        localRef: 'chan_slot_calls',
        sourceId: '982734800000000015',
        kind: 'text',
        name: 'slot-calls',
        categoryRef: 'cat_slots',
        position: 2,
        topic: 'Call a slot for the next bonus-buy stream.',
        rateLimitPerUser: 10,
        copyPolicy: 'member_chat',
      },
      {
        localRef: 'chan_big_wins',
        sourceId: '982734800000000016',
        kind: 'forum',
        name: 'big-wins',
        categoryRef: 'cat_slots',
        position: 3,
        topic: 'Post your monster wins. Use tags. Screenshots required.',
        rateLimitPerUser: 0,
        defaultForumLayout: 2,
        defaultSortOrder: 0,
        defaultAutoArchiveDuration: 4320,
        defaultThreadRateLimitPerUser: 5,
        defaultReaction: { emojiRef: 'emoji_jackpot' },
        copyPolicy: 'member_chat',
        forumTags: [
          { localRef: 'tag_10x', name: '10x-100x', moderated: false, emojiUnicode: '✨' },
          { localRef: 'tag_100x', name: '100x-500x', moderated: false, emojiUnicode: '🔥' },
          { localRef: 'tag_500x', name: '500x+', moderated: false, emojiRef: 'emoji_jackpot' },
          { localRef: 'tag_max', name: 'MAX WIN', moderated: true, emojiRef: 'emoji_whale' },
        ],
      },
      // ── VIP LOUNGE ───────────────────────────────────────────────────────────
      {
        localRef: 'chan_vip_chat',
        sourceId: '982734800000000017',
        kind: 'text',
        name: 'vip-chat',
        categoryRef: 'cat_vip',
        position: 0,
        topic: 'VIP & Whale only lounge.',
        copyPolicy: 'member_chat',
        overwrites: [
          { targetType: 'role', targetRef: 'role_everyone', allow: '0', deny: '1024' },
          { targetType: 'role', targetRef: 'role_vip', allow: '1024', deny: '0' },
        ],
      },
      {
        localRef: 'chan_whale_room',
        sourceId: '982734800000000018',
        kind: 'text',
        name: 'whale-room',
        categoryRef: 'cat_vip',
        position: 1,
        topic: 'Whales only. The highest tier.',
        copyPolicy: 'member_chat',
        overwrites: [
          { targetType: 'role', targetRef: 'role_everyone', allow: '0', deny: '1024' },
          { targetType: 'role', targetRef: 'role_whale', allow: '1024', deny: '0' },
        ],
      },
      // ── VOICE ────────────────────────────────────────────────────────────────
      {
        localRef: 'chan_voice_lounge',
        sourceId: '982734800000000019',
        kind: 'voice',
        name: 'Lounge',
        categoryRef: 'cat_voice',
        position: 0,
        bitrate: 96000,
        userLimit: 20,
        rtcRegion: null,
        videoQualityMode: 1,
        copyPolicy: 'member_chat',
      },
      {
        localRef: 'chan_voice_stream',
        sourceId: '982734800000000020',
        kind: 'voice',
        name: 'Stream Watch',
        categoryRef: 'cat_voice',
        position: 1,
        bitrate: 128000,
        userLimit: 50,
        videoQualityMode: 2,
        copyPolicy: 'member_chat',
      },
      {
        localRef: 'chan_afk',
        sourceId: '982734800000000021',
        kind: 'voice',
        name: 'AFK',
        categoryRef: 'cat_voice',
        position: 2,
        bitrate: 64000,
        userLimit: 0,
        copyPolicy: 'member_chat',
      },
    ],
    emojis: [
      { localRef: 'emoji_jackpot', sourceId: '982735000000000001', name: 'jackpot', asset: 'assets/aa11bb22cc33dd44.png' },
      { localRef: 'emoji_whale', sourceId: '982735000000000002', name: 'whale', asset: 'assets/bb22cc33dd44ee55.png' },
      { localRef: 'emoji_slot', sourceId: '982735000000000003', name: 'slot', asset: 'assets/cc33dd44ee55ff66.png' },
      { localRef: 'emoji_coin', sourceId: '982735000000000004', name: 'stakecoin', asset: 'assets/dd44ee55ff667700.png' },
      { localRef: 'emoji_fire', sourceId: '982735000000000005', name: 'onfire', asset: 'assets/ee55ff6677008811.gif', animated: true },
      { localRef: 'emoji_money', sourceId: '982735000000000006', name: 'moneyrain', asset: 'assets/ff6677008811992a.gif', animated: true },
      { localRef: 'emoji_vip', sourceId: '982735000000000007', name: 'vipcrown', asset: 'assets/667700881199aabb.png', roleRefs: ['role_vip', 'role_whale'] },
      { localRef: 'emoji_logo', sourceId: '982735000000000008', name: 'stakehaus', asset: 'assets/7700881199aabbcc.png' },
    ],
    stickers: [
      {
        localRef: 'sticker_bigwin',
        sourceId: '982735100000000001',
        name: 'BIG WIN',
        description: 'Stakehaus big-win celebration sticker',
        tags: '🎰',
        asset: 'assets/88991100aabbccdd.png',
        formatType: 1,
      },
      {
        localRef: 'sticker_whale',
        sourceId: '982735100000000002',
        name: 'whale splash',
        description: 'Whale-tier flex sticker',
        tags: '🐋',
        asset: 'assets/99aabbccdd001122.png',
        formatType: 1,
      },
    ],
    automod: [
      {
        localRef: 'am_scam_links',
        sourceId: '982735200000000001',
        name: 'Block scam & impersonator links',
        eventType: 1,
        triggerType: 1,
        triggerMetadata: {
          keywordFilter: ['free*nitro', 'steamcommunity*gift', 'discordgift*'],
          regexPatterns: ['(?i)stakeh[a4]us-?(giveaway|drop)\\.(xyz|info|net)'],
          allowList: ['https://whop.com/stakehaus'],
        },
        actions: [
          { type: 1, customMessage: 'Blocked: suspected scam link. Only trust links in #links.' },
          { type: 2, alertChannelRef: 'chan_mod_log' },
        ],
        enabled: true,
        exemptRoleRefs: ['role_admin', 'role_mod'],
        exemptChannelRefs: ['chan_links'],
      },
      {
        localRef: 'am_spam',
        sourceId: '982735200000000002',
        name: 'Spam content filter',
        eventType: 1,
        triggerType: 3,
        triggerMetadata: {},
        actions: [{ type: 1, customMessage: 'Please slow down — that looked like spam.' }],
        enabled: true,
        exemptRoleRefs: ['role_admin', 'role_mod'],
      },
      {
        localRef: 'am_mention_spam',
        sourceId: '982735200000000003',
        name: 'Mention raid protection',
        eventType: 1,
        triggerType: 5,
        triggerMetadata: { mentionTotalLimit: 6, mentionRaidProtectionEnabled: true },
        actions: [
          { type: 1 },
          { type: 3, durationSeconds: 600 },
          { type: 2, alertChannelRef: 'chan_mod_log' },
        ],
        enabled: true,
        exemptRoleRefs: ['role_admin', 'role_mod'],
      },
    ],
    bots: [
      {
        localRef: 'bot_mee6',
        sourceId: '159985870458322944',
        name: 'MEE6',
        vendorGuess: 'MEE6',
        inviteUrl: 'https://mee6.xyz/add',
        reconfigureNotes: [
          'leveling + rank roles',
          'reaction roles in #role-select',
          'welcome messages in #welcome',
          'XP-gated channels',
        ],
        configTraces: [
          { kind: 'managed_role', where: 'role: MEE6', ref: 'role_mee6', detail: 'leveling/rank role' },
          { kind: 'permission_overwrite', where: '#role-select overwrite', ref: 'chan_role_select', detail: 'reaction-role message' },
          { kind: 'webhook', where: "webhook 'MEE6' in #welcome", ref: 'chan_welcome', detail: 'join announcements' },
        ],
      },
      {
        localRef: 'bot_whop',
        sourceId: '878770893021847603',
        name: 'Whop',
        vendorGuess: 'Whop',
        inviteUrl: 'https://whop.com/discord',
        reconfigureNotes: [
          'connect the Stakehaus Whop product',
          'gate VIP + Whale roles by membership',
          'sync purchases → role grants',
        ],
        configTraces: [
          { kind: 'integration', where: 'Whop membership integration', ref: null, detail: 'grants role_vip / role_whale on purchase' },
          { kind: 'permission_overwrite', where: '#vip-chat overwrite', ref: 'chan_vip_chat', detail: 'gated by VIP role' },
        ],
      },
      {
        localRef: 'bot_ticket',
        sourceId: '557628352828014614',
        name: 'Ticket Tool',
        vendorGuess: 'Ticket Tool',
        inviteUrl: 'https://tickettool.xyz/',
        reconfigureNotes: [
          'recreate support panel & ticket categories',
          're-add staff role permissions',
          'restore transcript channel',
        ],
        configTraces: [
          { kind: 'webhook', where: "webhook 'Ticket Tool' in #faq", ref: 'chan_faq', detail: 'support panel message' },
          { kind: 'permission_overwrite', where: '#mod-log overwrite', ref: 'chan_mod_log', detail: 'transcript posting' },
        ],
      },
    ],
    content: [
      {
        channelRef: 'chan_rules',
        hasInteractiveComponents: false,
        messages: [
          {
            authorName: 'Stakehaus',
            authorIsBot: false,
            pinned: true,
            content: 'Welcome to **Stakehaus**. By staying here you agree to the rules below. 18+ only — gamble responsibly.',
            embeds: [
              {
                title: 'Stakehaus Rules',
                color: 0x6d28d9,
                description: 'Be respectful. No scams, no shilling, no begging. Full perks at https://whop.com/stakehaus',
                footerText: 'Stakehaus | Slots & Casino',
                fields: [
                  { name: '1. Respect everyone', value: 'No harassment, hate speech, or witch-hunting.', inline: false },
                  { name: '2. No advertising', value: 'No unsolicited links, DMs, or self-promo.', inline: false },
                  { name: '3. 18+ only', value: 'This is a gambling community. Must be of legal age.', inline: false },
                  { name: '4. Gamble responsibly', value: 'Never bet more than you can afford to lose.', inline: false },
                ],
              },
            ],
          },
        ],
      },
      {
        channelRef: 'chan_welcome',
        hasInteractiveComponents: false,
        messages: [
          {
            authorName: 'Stakehaus',
            authorIsBot: false,
            pinned: true,
            content: 'Glad to have you in the haus.',
            embeds: [
              {
                title: 'Welcome to Stakehaus 🎰',
                color: 0x6d28d9,
                description: 'Pick up your roles in #role-select, then jump into #general. Unlock VIP & bonuses at https://whop.com/stakehaus',
                url: 'https://whop.com/stakehaus',
                thumbnailUrl: 'https://cdn.stakehaus.example/logo.png',
                fields: [
                  { name: 'Start here', value: 'Read #rules → grab roles in #role-select.', inline: true },
                  { name: 'Go VIP', value: '[Join Stakehaus VIP](https://whop.com/stakehaus)', inline: true },
                ],
              },
            ],
          },
        ],
      },
      {
        channelRef: 'chan_links',
        hasInteractiveComponents: false,
        messages: [
          {
            authorName: 'Stakehaus',
            authorIsBot: false,
            pinned: true,
            content: 'Official Stakehaus links only — anything else is a scam.',
            embeds: [
              {
                title: 'Official Links',
                color: 0x6d28d9,
                description: 'Bookmark these. Staff will never DM you first.',
                fields: [
                  { name: 'VIP / Whop', value: 'https://whop.com/stakehaus', inline: false },
                  { name: 'Twitch', value: 'https://twitch.tv/stakehaus', inline: true },
                  { name: 'YouTube', value: 'https://youtube.com/@stakehaus', inline: true },
                  { name: 'X / Twitter', value: 'https://x.com/stakehaus', inline: true },
                ],
              },
            ],
          },
        ],
      },
      {
        channelRef: 'chan_role_select',
        hasInteractiveComponents: true,
        messages: [
          {
            authorName: 'MEE6',
            authorIsBot: true,
            pinned: true,
            content: 'Pick your roles below to customize your Stakehaus experience.',
            embeds: [
              {
                title: 'Self-Assign Roles',
                color: 0x6d28d9,
                description: 'Click a button to toggle a role. Click again to remove it.',
              },
            ],
            componentSummary: [
              'button: 🔔 Drops Ping',
              'button: 🎁 Giveaway Ping',
              'button: 🎥 Content Creator',
              'select: Region (NA / EU / OCE / Other)',
            ],
          },
        ],
      },
    ],
    brandTokens: [
      { kind: 'name', value: 'Stakehaus', occurrences: 21, sources: ['server name', 'role: Stakehaus VIP', '#rules embed', '#welcome embed', '#links embed', 'emoji: stakehaus'] },
      { kind: 'color', value: '#6d28d9', occurrences: 12, sources: ['role: Owner', 'role: Stakehaus VIP', 'category: VIP LOUNGE', '#rules embed', '#welcome embed'] },
      { kind: 'url', value: 'https://whop.com/stakehaus', occurrences: 6, sources: ['#welcome topic', '#rules topic', '#rules embed', '#welcome embed', '#links embed', 'automod allowList'] },
      { kind: 'url', value: 'https://twitch.tv/stakehaus', occurrences: 1, sources: ['#links embed'] },
    ],
  });
}
